# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Tests

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main, develop]

env:
    JWT_SECRET: ${{secrets.JWT_SECRET}}
    JWT_EXPIRATION_TIME: ${{secrets.JWT_EXPIRATION_TIME}}
jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x, 18.x]

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
                  cache-dependency-path: ./server/package-lock.json
            - name: NPM clean install
              working-directory: ./server
              run: npm ci
            - name: NPM test
              working-directory: ./server
              run: npm test
